version: '3'

services:
  whoami:
    image: containous/whoami
    container_name: whoami
    security_opt:
      - no-new-privileges:true
   labels:
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_BASE_URL}`)"

    networks:
      - traefik

networks:
  traefik:
    external: true
