version: '3'

services:
  whoami:
    image: containous/whoami
    container_name: whoami
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.http.routers.${PROJECT_NAME_HTTPS}.rule=Host(`${PROJECT_BASE_URL_HTTPS}`)"
      - "traefik.http.routers.${PROJECT_NAME_HTTPS}.tls=true"

      # Next 4 are redirect to https
      - "traefik.http.middlewares.${PROJECT_NAME_HTTPS}_http.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME_HTTPS}_http.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME_HTTPS}_http.middlewares=${PROJECT_NAME_HTTPS}_http"
      - "traefik.http.routers.${PROJECT_NAME_HTTPS}_http.rule=Host(`${PROJECT_BASE_URL_HTTPS}`)"

    networks:
      - traefik

networks:
  traefik:
    external: true
